---
- hosts: all
  become: yes

  tasks:
    - name: Ensure chrony (for time synchronization) is installed.
      apt:
        name: chrony
        state: present
    - name: Ensure chrony is running.
      service:
        name: chronyd
        state: started
        enabled: yes
    - name: Install dev packages
      apt:
        name:
          - git
          - curl
          - wget
          - zsh
        state: present
